base: /
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    websiteTitle: ''
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: de
    languageId: 0
rootPageId: 1
websiteTitle: 'Fritzifanten - Ihre liebevolle Tagesmutter in Brühl (Baden)'
